### ISSUE TITLE
How to prepare data for model 

### ISSUE THREAD

**Issue by talhaanwarch** [hfawaz/dl-4-tsc#11]
Greetings. First of all thanks for such wonder full work in time series domain. I want to know how to prepare data that can feed to model you have listed.
What i am doing is reshaping them as follows

`72x18x30000`

where 72 are number of subjects/examples. Each example has 18 channels, and each channel has 30,000 data points. I have add `channels_first` in keras layer.
Let me know, please, is my input shape is correct

**Comment by hfawaz** [comment]
Hello, 

Thanks for using the code. 

Indeed I think that if you are using ```channels_first``` then it is correct.

**Comment by talhaanwarch** [comment]
I have tried `python3 main.py TSC Wafer fcn _itr_8`. It said `Method:  TSC Wafer fcn _itr_8`
`Already done`
