### ISSUE TITLE
Some errors occured when running mcdd and twiesn

### ISSUE THREAD

**Issue by welcomeyou2019** [hfawaz/dl-4-tsc#12]
When I try to run the model of mcdd and twiesn, something wrong occured, can you have a look. Thank you.
<img width="976" alt="Screen Shot 2019-10-28 at 9 51 53 AM" src="https://user-images.githubusercontent.com/38488713/67646329-97310d00-f968-11e9-8c0d-6e1095bc1616.png">
<img width="1369" alt="Screen Shot 2019-10-28 at 9 53 54 AM" src="https://user-images.githubusercontent.com/38488713/67646391-dc553f00-f968-11e9-81a1-0f96014ada50.png">

**Comment by hfawaz** [comment]
Hi, 

For the second image it is a warning (because tlenet is not accurate). 

For the first image, can you specify which dataset you are using ? 

Thanks
