### ISSUE TITLE
What is the version number of tensorflow and keras used

### ISSUE THREAD

**Issue by LMMOO-LJQ** [hfawaz/dl-4-tsc#13]
First, thank for your variable work.
When I run the model, many Errors in tensorflow have appeared, so want to know the version number of tensorflow and keras you used.

**Comment by hfawaz** [comment]
Thanks for your interest. 
At the time I used tensorflow 1.14, what type of errors you have ?

**Comment by LMMOO-LJQ** [comment]
Thank for your reply！ After upgrading my tensorflow to 1.14, the problem have been solved.
