### ISSUE TITLE
some error in utils.py

### ISSUE THREAD

**Issue by Pauler99** [hfawaz/dl-4-tsc#14]
In the viz_cam function，“unresolved reference ‘spline’” error occurred.

**Comment by hfawaz** [comment]
Yes thanks for pointing it out. 

The spline is [deprecated](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.interpolate.spline.html) now. 

I personally use [pandas.Series.interpolate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.interpolate.html) now. 

Hope this helps.
