### ISSUE TITLE
Also some error on utils.py

### ISSUE THREAD

**Issue by LMMOO-LJQ** [hfawaz/dl-4-tsc#16]
First, thank you for your program shared. 
Then in lines: 313 314 338 339 in utils.py. 
['acc'] and ['val_acc'] should be modified to ['accuracy'] and ['val_accuracy']. 
If not it will report that : Error : ' acc '.

**Comment by hfawaz** [comment]
Yes you are right indeed this changed with newer versions of keras thanks for documenting it.
