### ISSUE TITLE
can be your code used for multivariate time series classification

### ISSUE THREAD

**Issue by Sandy4321** [hfawaz/dl-4-tsc#17]
great code thanks
only can you clarify if
can be your code used for multivariate time series classification
when data is mixter of continues and categorical variables for each time sample?
like
https://github.com/alan-turing-institute/sktime/blob/master/examples/multivariate_time_series_classification.ipynb

**Comment by hfawaz** [comment]
Hi thanks for the interest. 
I have not investigated the application to a mix of categorical, but I believe you can transform the categorical data to a sort of continuous values.

**Comment by snowaa007** [comment]
Hi, can you update the accuracies of 30 UEA MTS datasets?
