### ISSUE TITLE
run time

### ISSUE THREAD

**Issue by vibha15** [hfawaz/dl-4-tsc#19]
Hi Dr Fawaz,
Thanks for providing the deep learning tsc codes. I am about to begin my work which is also on the similar track. So, i downloaded the code from your page https://github.com/hfawaz/dl-4-tsc and cofee data (both in .zip) from UCR archive to my machine and ran the coffee data as mentioned in this page under Code section.
Could your please tell me how long this one line (python3 main.py TSC Coffee fcn _itr_8) code should take to execute? if each prerequisite is completed already. Thank you. 

Regards,
Vibha

**Comment by hfawaz** [comment]
Hi Vibha, 

Thanks for your interest. 
The run time depends on your hardware configuration, if you are using a GPU it should take about 20 minutes. If you are using CPU I am not sure, but definitely longer than GPU. 
Best,

**Comment by vibha15** [comment]
Hi Dr Fawaz,

Thank you so much for your help. I was using HPC, but did not use GPU. Thanks for your time.

Regards,
Vibha
________________________________
