### ISSUE TITLE
unable to find best_model

### ISSUE THREAD

**Issue by paullouBenedick** [hfawaz/dl-4-tsc#21]
Hi,

For some datasets (i.e. DodgerLoopDay), I got an error when running FCN classifier.
Actually, I got the error "OSError: Unable to open file (unable to open file: name = 'xxx/results/fcn/UCRArchive_2018/DodgerLoopDay/best_model.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)"
It seems that there is no best_model.hdf5 saved.

Do you know how to manage/fix this issue?

Thank you

**Comment by hfawaz** [comment]
Hi, 
For some datasets (i.e. Dodger*) you should make sure that the model is being trained on the version that is normalized in the UCR archive (there should be a folder that contains another version of these datasets).

**Comment by paullouBenedick** [comment]
Well thank you, but where can I find this folder? I downloaded datasets from UCR but there is only one folder per dataset and nothing else.

thx

**Comment by hfawaz** [comment]
When I downloaded the UCr archive it contained the following folder: "Missing_value_and_variable_length_datasets_adjusted"

**Comment by paullouBenedick** [comment]
Thank you I finally found it. 
I will try it and close the issue if it works.

Thanks for your help
