### ISSUE TITLE
How to analyze the CD diagram

### ISSUE THREAD

**Issue by peter943** [hfawaz/dl-4-tsc#31]
Hi, 
  I read your paper (Deep learning for time series classification: a review ) these days . I am always confused about how to analyze the CD diagram. For example, the FIg.7 in your paper. There are connections between MLP, Time-CNN, and TWIESN, as well as between TWIESN and MCDCNN. That means there's no statistical difference between MLP, Time-CNN and TWIESN, and there's no statistical difference between TWIESN and MCDCNN. 
  So, there is no statistical difference between MLP and MCDCNN? I doubt the correctness of this conclusion. Because these four methods are not connected by a single connection. But I do not know what the right conclusion is, could you please give me some help? Thanks a lot.
![image](https://user-images.githubusercontent.com/52994917/87264426-81fa0f80-c4f2-11ea-8569-55eda37099ff.png)

**Comment by hfawaz** [comment]
Hello, 
Thanks for your interest in our project and much thanks for sharing your thoughts here. 
In the cd diagram, every group of classifiers that are connected in a single thick horizontal line are considered to have a non significant difference between them. 
Therefore, you would interpret this figure by saying that: 
- MLP, Time-CNN and TWIESN are not significantly different.
- TWIESN and MCDCNN are not significantly different. 
- MCDCNN and Time-CNN are significantly different.
- MCDCNN and  MLP are significantly different.
- MCDCNN and TWIESN are significantly different. 

Hope this helps

**Comment by peter943** [comment]
@hfawaz  Thank you for your help.
