### ISSUE TITLE
Is the data being pulled in N,T,F

### ISSUE THREAD

**Issue by sabooakhter** [hfawaz/dl-4-tsc#36]
Hey Hassan,

Is the data that is being pulled in for the multivariate MTS data in the shape of (Number of Samples, Timesteps, Number of Features)?  Please inform, Thanks,

Sincerely,
Sohaib

**Comment by hadifawaz1999** [comment]
Hello,

The shape is (Number of Samples, TimeSteps, Number of Features) yes.
