### ISSUE TITLE
y_true vs y_test

### ISSUE THREAD

**Issue by Laoban-man** [hfawaz/dl-4-tsc#40]
Hi,
just a quick question. In twiesn.py, the fit method of the classifier asks for y_true and y_test but doesn't seem to use the latter for anything (it's used to define self.y_test but nothing else). Is there a difference between the two? I haven't looked in detail but I think there was a similar point in inception.py?
Cheers

**Comment by Nadiam75** [comment]
whats the difference between y_true & y_test?

**Comment by Gpialla** [comment]
Dear @Laoban-man & @Nadiam75 

*y_test* is the label OneHotEncoded, while *y_true* is the label as an integer.
*y_true* is defined in [main.py#L34](https://github.com/hfawaz/dl-4-tsc/blob/3ee62e16e118e4f5cfa86d01661846dfa75febfa/main.py#L34)

For convenience, all the classifiers have been coded using the same signature for the functions.
Thus, although *y_test* is not used in twiesn.py it may be used in another classifier.
