### ISSUE TITLE
The link to  Multivariate time series datasets is now missing

### ISSUE THREAD

**Issue by YaoDongAn** [hfawaz/dl-4-tsc#48]
Thank you for your works!

It's a great contribution for the study of time series classification.
I'm very interested on your works but I noticed that the link to  **Multivariate time series datasets** is now missing.

Can you help me fix that or give me another link？
Thank you very much

**Comment by Gpialla** [comment]
This archive was hosted on the website of Mustafa Gokce Baydogan [http://www.mustafabaydogan.com/](http://www.mustafabaydogan.com/). 
The link is broken and I can't find any new link on his website.
I think the best way would be to contact him directly :)

**Comment by YaoDongAn** [comment]
> This archive was hosted on the website of Mustafa Gokce Baydogan [http://www.mustafabaydogan.com/](http://www.mustafabaydogan.com/). 
> The link is broken and I can't find any new link on his website.
> I think the best way would be to contact him directly :)

thank you for your reply, I will try to access it.
cheers
