### ISSUE TITLE
How do you deal with data of varying length?

### ISSUE THREAD

**Issue by ghost** [hfawaz/dl-4-tsc#49]
such as "AllGestureWiimoteX" in UCRArchive_2018, it includes Nan in the train.tsv and test.tsv. How do you deal with this?
Thanks a lot to inform me.

**Comment by Gpialla** [comment]
Hi @GodFire6666 
The UCR Archive 2018 has 15 datasets that have either different lengths or missing values.
Datasets with different lengths were dealt with by padding the missing portions and missing data were replaced using interpolation.
The corrected datasets are located in the folder 'Missing_value_and_variable_length_datasets'.
All details are available on the briefing document of the UCR Archive page 16 [https://www.cs.ucr.edu/~eamonn/time_series_data_2018/BriefingDocument2018.pdf](https://www.cs.ucr.edu/~eamonn/time_series_data_2018/BriefingDocument2018.pdf).
