### ISSUE TITLE
vs SVM('rbf')?

### ISSUE THREAD

**Issue by fantoumas** [hfawaz/dl-4-tsc#5]

**Comment by hfawaz** [comment]
Hello,

Can you please provide details regarding you issue ? 

Thanks

**Comment by fantoumas** [comment]
Hello, I have given up on the DTW after reading your article, but I got better experimental results when I used SVM as a classifier for some data. I suggest you try it. I don't have such good experimental conditions for detailed analysis.


My English is not very good, thank you for your reply.
ArroeHead 0.85Beef 0.733BeetleFly 0.75BirdChicken 0.75Car 0.8166CinC_ECG_torso 0.247ItalyPowerDemand 0.9504


------------------ 原始邮件 ------------------
发件人: "Hassan ISMAIL FAWAZ"<notifications@github.com>;
发送时间: 2019年5月24日(星期五) 晚上9:00
收件人: "hfawaz/dl-4-tsc"<dl-4-tsc@noreply.github.com>;
抄送: "姜逸凡"<594143395@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hfawaz/dl-4-tsc] vs SVM('rbf')? (#5)




Hello,
 
Can you please provide details regarding you issue ?
 
Thanks

**Comment by fantoumas** [comment]
This is my code。


from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
C_range = np.logspace(-2,2,10)
gamma_range = np.logspace(-2,1,10)
para_grid = dict(gamma = gamma_range, C = C_range)
grid = GridSearchCV(SVC(kernel='rbf'), param_grid=para_grid)
grid.fit(x_train, y_train)

grid.score(x_test,y_test)




------------------ 原始邮件 ------------------
发件人: "Hassan ISMAIL FAWAZ"<notifications@github.com>;
发送时间: 2019年5月24日(星期五) 晚上9:00
收件人: "hfawaz/dl-4-tsc"<dl-4-tsc@noreply.github.com>;
抄送: "姜逸凡"<594143395@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hfawaz/dl-4-tsc] vs SVM('rbf')? (#5)




Hello,
 
Can you please provide details regarding you issue ?
 
Thanks

**Comment by hfawaz** [comment]
Hello, 

Thank you for sharing the results. 

Indeed SVM is considered to be a strong baseline. 

In [this paper](https://link.springer.com/content/pdf/10.1007%2Fs10618-016-0483-9.pdf), they tested it and found out to be close to Rotation Forest. 

Thanks again for sharing. 

Best,

**Comment by fantoumas** [comment]
Hello, thank you for your reply.
I have an idea,
Is it possible to combine 85 data sets of UCR into one larger unified data set? Like imagenet, using CNN should be able to train on time series data of different lengths.
Can I extract more powerful feature sequence information from so much data?
Different ECG data are similar to different car pictures, but in the field of computer vision, not only can different cars be distinguished,
It is also possible to distinguish between different faces.
The entire CNN is like a filter. If it is valid, the feature extracted by this method is on the simplest nearest neighbor algorithm (Euclidean distance -1NN), and it should also get good classification results.
Or on this basis, different classification algorithms are used for adjustment for different data.
The question is, how do you train your dataset to fit different categories of information?



Thanks again for sharing.





------------------ 原始邮件 ------------------
发件人: "Hassan ISMAIL FAWAZ"<notifications@github.com>;
发送时间: 2019年5月26日(星期天) 下午5:08
收件人: "hfawaz/dl-4-tsc"<dl-4-tsc@noreply.github.com>;
抄送: "姜逸凡"<594143395@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hfawaz/dl-4-tsc] vs SVM('rbf')? (#5)




Hello,
 
Thank you for sharing the results.
 
Indeed SVM is considered to be a strong baseline.
 
In this paper, they tested it and found out to be close to Rotation Forest.
 
Thanks again for sharing.
 
Best,

**Comment by fantoumas** [comment]
I mean is，


Or based on this, adjust the last few layers of the network according to different data.


What I mean may not be very clear, I hope you can understand. powerful=strong？haha




------------------ 原始邮件 ------------------
发件人: "Hassan ISMAIL FAWAZ"<notifications@github.com>;
发送时间: 2019年5月26日(星期天) 下午5:08
收件人: "hfawaz/dl-4-tsc"<dl-4-tsc@noreply.github.com>;
抄送: "姜逸凡"<594143395@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hfawaz/dl-4-tsc] vs SVM('rbf')? (#5)




Hello,
 
Thank you for sharing the results.
 
Indeed SVM is considered to be a strong baseline.
 
In this paper, they tested it and found out to be close to Rotation Forest.
 
Thanks again for sharing.
 
Best,

**Comment by hfawaz** [comment]
Hello, 

Thanks for sharing your ideas with us. 

I think this has been explored in [this paper](https://arxiv.org/abs/1805.03908). 

They pre-trained a network on a multi-class classification problem by fusing different TSC datasets.

You can try to test this with the ResNet architecture and see how this could affect the performance. 

Keep us up to date with your results ! 

Best,

**Comment by fantoumas** [comment]
Hello，
Thanks for sharing your ideas with me.


This is great job,
It's amazing to have a similar idea.
Adjusting the network structure may give better results.
It's already great.



Best，


------------------ 原始邮件 ------------------
发件人: "Hassan ISMAIL FAWAZ"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 下午3:17
收件人: "hfawaz/dl-4-tsc"<dl-4-tsc@noreply.github.com>;
抄送: "姜逸凡"<594143395@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hfawaz/dl-4-tsc] vs SVM('rbf')? (#5)




Hello,
 
Thanks for sharing your ideas with us.
 
I think this has been explored in this paper.
 
They pre-trained a network on a multi-class classification problem by fusing different TSC datasets.
 
You can try to test this with the ResNet architecture and see how this could affect the performance.

Keep us up to date with your results !
 
Best,
