### ISSUE TITLE
does it mean your code works for classification with mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [hfawaz/dl-4-tsc#9]
great code thanks
you give link to
The MTS archive, which contains the 13 multivariate time series datasets
does it mean your code works with mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?
etc

by the way do you know not NN github code for classification of mixture of categorical and continues data? let say data is not long enough to use NN?

**Comment by hfawaz** [comment]
Hello, 

Thanks for your inquiry and interest in our code. 

But for now the current models do not work on a mixture of categorical and continuous data. 

Best,
